production_ecommerce/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required


from . import views
app_name = 'account'
urlpatterns = [
    path('register/', views.registration_view, name="register"),
    path('login/', views.login_view, name='login'),
    path('login-required/', views.login_view_required, name='login_required'),
    path('logout/', views.logout_view, name='logout'),
    path('update/', views.account_view, name='update'),
    path('product/history/', views.account_fitler, name='filter'),
    path('client/register/', views.registration_client_view, name='client'),
    path('settings/', views.accountSettings, name='accountsettings'),
    path('settings/', views.account_view, name='settings'),
]

production_ecommerce/ecommerce/urls.py
from django.urls import path
from ecommerce import views
from .views import (
    ItemDetailView,
    HomeView,
    Form_view, Vendor_option,
    Plumber, SellMessage,
    Electrical, Laundry, Garden, Tilin, Cleaning, Carpentry,
    ServiceDetail, ProductDetail, Shop, CarDetail, HouseDetail,
)

app_name = 'ecommerce'

urlpatterns = [
    path('nivoslider/', views.nivoslider, name='nivo'),
    path('try/', views.tr, name='try'),
    path('admin/', views.admin, name='admin'),
    path('', HomeView.as_view(), name='home'),
    path('vendor/', Vendor_option.as_view(), name='vendor_options'),
    path('tryform/', Form_view.as_view(), name='tryform'),
    path('settings/', views.accountSettings, name='settingss'),
    #path('', views.slider, name='home'),
    path('send/request/', views.send_mail, name='send_mail'),
    path('advertise/vendor/', views.vendor_sell_multiple, name='multiple'),
    path('vendor/single/multiple/', views.vendor_sell, name='singlemultiple'),
    path('messages/', SellMessage.as_view(), name='message'),
    path('sell/product/', views.sell, name='sell'),
    path('sell/house/', views.rent_house, name='rent_house'),
    path('sell/car/', views.rent_car, name='rent_car'),
    path('sell/car/', views.rent_car_multiple, name='car-multiple'),
    path('order/food/', views.food, name='food'),
    path('buy/product/', Shop.as_view(), name='shop'),
    path('service/plumbing/', Plumber.as_view(), name='plumbing'),
    path('service/electrical/', Electrical.as_view(), name='electrical'),
    path('service/carpentry/', Carpentry.as_view(), name='carpentry'),
    path('service/garding/', Garden.as_view(), name='garden'),
    path('service/laundry/', Laundry.as_view(), name='laundry'),
    path('service/tilin/', Tilin.as_view(), name='tilin'),
    path('service/cleaning/', Cleaning.as_view(), name='cleaning'),
    path('service/detail/<int:pk>/', ServiceDetail.as_view(), name='detail'),
    path('<slug:slug>/', ProductDetail.as_view(), name='product-details'),
    path('car/detail/<int:pk>/', CarDetail.as_view(), name='cardetail'),
    path('house/details/<int:pk>/', HouseDetail.as_view(), name='housedetail'),
    path('service/electrical/', views.electrical, name='electrical'),
    path('options/', views.vendor_options, name='vendor-options'),
    path('dashboard/', views.vendor_sell, name='vendor_sell'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
]

production_ecommerce/production_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from ecommerce.sitemaps import ProductSitemap

sitemaps = {
    'product': ProductSitemap
}

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('ecommerce.urls')),
    path('account/', include('account.urls')),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps},
    name = 'django.contrib.sitemaps.views.sitemap')

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

production_ecommerce/vendorprofile/urls.py
from django.urls import path
from vendorprofile import views

app_name = 'vendorprofile'
urlpatterns = [
    path('home',views.index,name="home"),
    path('help',views.help,name="help"),
    ]

production_ecommerce/chat_app/models.py
from django.db import models

# Create your models here.


class Memory(models.Model):
    key = models.TextField()
    value = models.TextField()


class Conversation(models.Model):
    query = models.TextField()
    response = models.TextField()

    def __unicode__(self):
        return self.query

production_ecommerce/ecommerce/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect, HttpResponse
from django.contrib.auth.models import User, auth
from django.views import generic
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, View
from django.shortcuts import redirect
from django.utils import timezone
from ecommerce.forms import ContactForm, ProductForm, Quick_ServiceForm, VendorForm, VendorImageForm, HouseImageForm, CarImageForm, RentCarForm, ProductImageForm, RentHouseForm, OrderFoodForm
from django.views.generic import TemplateView
from .import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from ecommerce.models import Vendor, VendorImage, Product, ProductImage, Quick_Service, FoodImage, CarImage, HouseImage, RentCar, RentHouse
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.edit import CreateView
from django.forms import modelformset_factory
from django.conf import settings
from django.core import serializers
from account.models import UserVendor
from django.core.mail import send_mail, EmailMessage
from django.conf import settings
from django import template
from django.template.loader import get_template
from django.contrib import messages
import json
from hitcount.views import HitCountDetailView
from django.db.models import Count

def create_ref_code():
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=20))


def tr(request):
    return render(request, 'ecommerce/base2.html')


class Form_view(TemplateView):
    template_name = 'ecommerce/sell.html'

    def get(self, request):
        form = ProductForm()
        return render(request, self.template_name, {'form': form})


class HomeView(ListView):
    model = Product
    template_name = 'ecommerce/inner.html'
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['products'] = Product.objects.all()[:10]
        context['automobile'] = RentCar.objects.all()[:5]
        context['vendors'] = Vendor.objects.all()[:10]
        context['related_products'] = Product.objects.annotate(tag_count=Count('tags')).order_by('tag_count', 'posted_date')
        context['bestseller'] = Product.objects.filter(category='')
        context['most_active'] = Product.objects.annotate(npost=Count('title')).order_by('-npost')[:5]
        context['slides'] = Vendor.objects.all().order_by('-date')[:15]
        context['cars'] = RentCar.objects.all().order_by('-pub_date')[:8]
        context['houses'] = RentHouse.objects.all().order_by('-post_date')[:8]
        return context



def account_view(request):

    if not request.user.is_authenticated:
        return redirect("account:login")

    context = {}
    if request.POST:
        form = UserVendorUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()

    else:
        form = UserVendorUpdateForm(
            initial={
                "email": request.user.email,
                "username": request.user.username,
                "contact": request.user.contact,
                "location": request.user.location,
                "profession": request.user.profession,
                "experience": request.user.experience,
            }
        )

    context['account_form'] = form

    return render(request, "account/settings.html", context)

def account_fitler(request):
    items = Product.objects.filter(vendor=request.user).order_by('-posted_date')
    context = {
        'items': items,
    }
    return render(request, 'account/account_settings.html', context)


def admin(request):
    return render(request, 'admin/base_site.html')


def slider(request):
    # change the time field in all models to posted date for uniformitty
    items = Product.objects.all()[:8]
    slides = Vendor.objects.all().order_by('-date')[:15]
    vendor = Vendor.objects.all().order_by('-date')
    cars = RentCar.objects.all().order_by('-pub_date')[:8]
    house = RentHouse.objects.all().order_by('-post_date')[:8]
    context = {
        'house': house,
        'cars': cars,
        'slides': slides,
        'items': items,
        'vendor': vendor,
    }
    return render(request, "ecommerce/temp.html", context)


def any_view(request):
    posts = Article.objects.all().order_by("-pub_date")[:5]
    return render(request, "show/temp.html", {'posts': posts})


class SellMessage(SuccessMessageMixin, CreateView):
    template_name = 'ecommerce/sell.html'
    form_class = ProductForm
    success_url = 'ecommerce:home'
    seccess_message = 'be ready to meet your buyers soon!'


class VendorView(ListView):
    model = Vendor
    template_name = 'ecommerce/index.html'
    paginate_by = 10
    context_object_name = 'vendor'

    def get_queryset(self):
        return Vendor.objects.all()


@login_required(login_url='/account/login-required/')
def sell(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        imageform = forms.ProductImageForm(request.POST, request.FILES)
        img = request.FILES.getlist('productimages')
        if form.is_valid() and imageform.is_valid():
            instance = form.save(commit=False)
            instance.vendor = request.user
            instance.save()
            for f in img:
                image_instance = ProductImage(image=f, vendor=instance)
                image_instance.save()
            messages.success(request, "Product uploaded successfully and it's ready for purchase!!")
        else:
            messages.error(request, "Error!!, due to internal error or internet connectivity")
            form = VendorForm()
            imageform = ProductImageForm()
    return render(request, 'ecommerce/sell.html', {'form': ProductForm(), 'imageform': ProductImageForm()})



@login_required(login_url='/account/login-required/')
def vendor_sell(request):
    if request.method == 'POST':
        form = VendorForm(request.POST)
        file_form = forms.VendorImageForm(request.POST, request.FILES)
        files = request.FILES.getlist('images')
        if form.is_valid() and file_form.is_valid():
            instance = form.save(commit=False)
            instance.vendor = request.user
            instance.save()
            for f in files:
                file_instance = VendorImage(file=f, vendor=instance)
                file_instance.save()
            messages.success(request, "Vendor created successfully, Good luck...!!")
        else:
            messages.error(request, "Error, due to internal or internet connectivity!!")
            form = VendorForm()
            file_form = VendorImageForm()
    return render(request, 'ecommerce/vendor_profile.html', {'form': VendorForm(), 'file_form': VendorImageForm()})


@login_required(login_url='/account/login-required/')
def vendor_sell_multiple(request):
    # number of images to be allowed
    ImageFormSet = modelformset_factory(VendorImage, fields=('file',), extra=5)
    if request.method == "POST":
        form = VendorForm(request.POST)
        formset = ImageFormSet(request.POST or None, request.FILES or None)
        if form.is_valid() and formset.is_valid():
            vendor = form.save(commit=False)
            vendor.vendor = request.user
            vendor.slug = slugify(vendor.title)
            vendor.save()
            for f in formset:
                try:
                    photo = VendorImage(vendor=vendor, file=f.cleaned_data['file'])
                    photo.save()
                except Exception as e:
                    break
            messages.success(request, 'succeffuly')
            return redirect('ecommerce:vendor_options')
            # this helps to not crash if the user
            # do not upload up to the max.
    else:
        form = VendorForm()
        formset = ImageFormSet(queryset=VendorImage.objects.none())
        context = {
            'form': form, 'formset': formset,
        }
    return render(request, 'ecommerce/vendor_profile.html', {'form': form, 'formset': formset})


@login_required(login_url='/account/login-required/')
def rent_car_multiple(request):
    # number of images to be allowed
    ImageFormSet = modelformset_factory(CarImage, fields=('image',), extra=5)
    if request.method == "POST":
        form = RentCarForm(request.POST)
        formset = ImageFormSet(request.POST or None, request.FILES or None)
        if form.is_valid() and formset.is_valid():
            vendor = form.save(commit=False)
            vendor.vendor = request.user
            vendor.save()
            for f in formset:
                try:
                    photo = CarImage(vendor=vendor, image=f.cleaned_data['image'])
                    photo.save()
                except Exception as e:
                    break
            messages.success(request, 'succeffuly')
            return redirect('ecommerce:home')
            # this helps to not crash if the user
            # do not upload up to the max.
    else:
        form = RentCarForm()
        formset = ImageFormSet(queryset=CarImage.objects.none())
        context = {
            'form': form, 'formset': formset,
        }
    return render(request, 'ecommerce/rent_car.html', {'form': form, 'formset': formset})


@login_required(login_url='/account/login-required/')
def rent_car(request):
    if request.method == 'POST':
        form = RentCarForm(request.POST)
        carimageform = forms.CarImageForm(request.POST, request.FILES)
        img = request.FILES.getlist('carimages')
        if form.is_valid() and carimageform.is_valid():
            instance = form.save(commit=False)

production_ecommerce/vendorprofile/views.py
from django.shortcuts import render,HttpResponse,render_to_response,HttpResponseRedirect
from django.contrib import auth
from vendorprofile.models import  Teacher
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404


import sys

import os
import datetime
import time
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

from django.shortcuts import get_object_or_404

__location__ = os.path.realpath(
    os.path.join(os.getcwd(), os.path.dirname(__file__)))
loc = os.path.join(__location__, 'media/')
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
image_dir = os.path.join(BASE_DIR, 'media')



def rhome(request):
    return HttpResponseRedirect('/home/')
def cpath(fpath):
    return os.path.join(__location__, fpath)
def onTeacher(request):
      if request.session.get('teacher'):
         return Teacher.objects.get(emailId=request.session.get('teacher'))
      else:
         return None



def index(request):
    if request.session.get('teacher',None):
        unsetDepartmentCourseBatch(request)
        teacher=onTeacher(request)
        return render(request,'vendorprofile/home.html',{"user":teacher,'range':range(2010,2222)})
    else:

       return HttpResponseRedirect('/')



def isLogin(func):
      def newFunc(request):
          if onTeacher(request) == None :
                  return HttpResponseRedirect("/login/")
          else:
             return func(request)
      return newFunc

def login(request):
    error=""
    if request.POST:
     data=request.POST
     emailId=data.get('emailId')
     password=data.get('password')
     print (emailId,password)
     flag=False
     try:
          teacher=Teacher.objects.get(emailId=emailId)

          if teacher.emailId==emailId and teacher.password==password:
               flag=True
               request.session['teacher']=emailId
               return HttpResponseRedirect('/home')
          else:
               flag=False
     except Exception as e:
          error=e
    return render(request,'vendorprofile/login.html',{"error":error})


@isLogin
def logout(request):
      del request.session['teacher']
      return HttpResponseRedirect('/home')


@isLogin
def help(request):
      teacher = onTeacher(request)
      return render(request,'vendorprofile/help.html',{'user':teacher})
#-----------------------------------------------------------------------#



#-----Admin -------------#
@login_required(login_url='/admin/login/')
def adminhelp(request):
     user={}
     return  render(request,'vendorprofile/adminhelp.html',{'user':user})

@login_required(login_url='/admin/login/')
def admin(request):
     user={}
     return  render(request,'vendorprofile/admin.html',{'user':user})


@login_required(login_url='/admin/login/')
def domore(request):
     user={}
     return render(request,'vendorprofile/domore.html',{'user':user})

production_ecommerce/ecommerce/templates/ecommerce/account_settings.html
{% extends "ecommerce/base.html" %}
{% block select %}
<style>
    .profile-pic{
        max-width: 200px;
        max-height: 200px;
        margin: 0 auto;
        border-radius: 50px;
    }
</style>

<br>
<div class="row">
        <div class="col-md-3">
                <div class="card card-body">
                        <a class="btn btn-warning" href="#">&#8592; Back to Profile</a>
                        <hr>
                        <h3 style="text-align: center">Account Setting</h3>
                        <hr>
                        <img class="profile-pic" src="{{request.user.profile.profile_image.url}}">
                </div>
        </div>
        <div class="col-md9">
                <div class="card card-body">
                        <form method="POST" action="#" enctype="multipart/form-data">
                            {% csrf_token %}
                                {{forms}}
                            <input class="btn btn-primary" type="submit" name="Update Information">
                        </form>
                </div>
        </div>
</div>
{% endblock %}

production_ecommerce/ecommerce/templates/ecommerce/anotherdetail.html
https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.slim.min.js
https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css
https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js

production_ecommerce/ecommerce/templates/ecommerce/carpentry.html
{% extends "ecommerce/base/index-example.html" %}

{% block select %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!-- Team -->
<div class="breadcrumb-area mt-30">
    <div class="container">
        <div class="breadcrumb">
            <ul class="d-flex align-items-center">
                <li><a href="{% url 'ecommerce:home' %}">Home</a></li>
                <li class="active"><a href="{% url 'ecommerce:vendor_options' %}">Services</a></li>
                <li class="active"><a href="{% url 'ecommerce:carpentry' %}">Carpentry</a></li>
            </ul>
        </div>
    </div>
    <!-- Container End -->
</div>
<div class="back">
    <section id="team" class="pb-5">

        <div class="container">
            <h5 class="section-title h1">CARPENTRY SERVICE</h5>
            <div class="row">
                <!-- Team member -->
                {% if vendor %}
                {% for carpentry in vendor %}
                <div class="col-xs-12 col-sm-6 col-md-3">
                    <div class="image-flip" ontouchstart="this.classList.toggle('hover');">
                        <div class="mainflip">
                            <div class="frontside">
                                <div class="card">
                                    <div class="card-body text-center">

                                        <p><img class=" img-fluid"  src="{{carpentry.first_image.file.url}}" alt="card image"></p>
                                        <h4 class="card-title">{{carpentry.trade_name}}</h4>
                                        <p class="card-text">{{ carpentry.service_description|truncatewords:"9"}}.</p>
                                        <a href="#" class="btn btn-primary btn-sm"><i class="fa fa-plus"></i></a>

                                    </div>

                                </div>
                            </div>
                            <div class="backside">
                                <div class="card">
                                    <div class="card-body text-center mt-4">
                                        <h4 class="card-title">{{carpentry.trade_name}}</h4>
                                        <p class="card-text">{{carpentry.service_description|truncatewords:"10"}}</p>
                                        <ul class="list-inline">
                                            <li class="list-inline-item">
                                                <a class="social-icon text-xs-center" href="{{carpentry.get_absolute_url}}">
                                                    <i >VIEW DETAILS</i>
                                                </a>
                                            </li>

                                        </ul>
                                    </div>
                                </div>
                            </div>

                        </div>

                    </div>
                </div>
                {% endfor %}
                {% else %}
                <ul class="list-inline">
                    <li class="list-inline-item">
                            <h3><i >NO CARPENTERS YET</i</h3>
                    </li>

                </ul>
                {% endif %}
                <!-- ./Team member -->
                <!-- Team member -->

                <!-- ./Team member -->

            </div>
        </div>
    </section>
</div>
{% endblock %}

production_ecommerce/ecommerce/templates/ecommerce/client.html
{% extends 'ecommerce/base.html' %}
{% load crispy_forms_tags %}
{% block select %}
        <div class="register-account ptb-100 ptb-sm-60">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="register-title">
                            <h3 class="mb-10">REGISTER ACCOUNT AS A CLIENT</h3>
                            <p class="mb-10">If you already have an account with us, please login at the login page.</p>
                        </div>
                    </div>
                </div>
                <!-- Row End -->
                <div class="row">
                    <div class="col-sm-12">
                        <form  method="POST" class="form-register" action="{% url 'account:client' %}">
                            {% csrf_token %}
                            <fieldset>
                                <legend>Your Personal Details</legend>


                                <div class="form-group d-md-flex align-items-md-center">
                                    <label class="control-label col-md-2" for="email"><span class="require">*</span>Email</label>
                                    <div class="col-md-10">

                                        {{registration_form.email}}
                                    </div>
                                </div>
                                <div class="form-group d-md-flex align-items-md-center">
                                    <label class="control-label col-md-2" for="number"><span class="require">*</span>Contact</label>
                                    <div class="col-md-10">

                                        {{ registration_form.contact}}
                                    </div>
                                </div>
                                <div class="form-group d-md-flex align-items-md-center">
                                    <label class="control-label col-md-2" for="text"><span class="require">*</span>Name</label>
                                    <div class="col-md-10">
                                        {{ registration_form.username}}
                                    </div>
                                </div>
                            <fieldset>
                                <legend>Your Password</legend>
                                <div class="form-group d-md-flex align-items-md-center">
                                    <label class="control-label col-md-2" for="pwd"><span class="require">*</span>Password</label>
                                    <div class="col-md-10">
                                        {{registration_form.password1}}
                                    </div>
                                </div>
                                <div class="form-group d-md-flex align-items-md-center">
                                    <label class="control-label col-md-2" for="pwd-confirm"><span class="require">*</span>Confirm Password</label>
                                    <div class="col-md-10">

                                        {{registration_form.password2}}
                                    </div>
                                </div>
                            </fieldset>
                            <fieldset class="newsletter-input">
                                <legend>Newsletter</legend>
                                <div class="form-group d-md-flex align-items-md-center">
                                    <label class="col-md-2 control-label">Subscribe</label>
                                    <div class="col-md-10 radio-button">
                                         <label class="radio-inline"><input type="radio" name="optradio">Yes</label>
                                         <label class="radio-inline"><input type="radio" name="optradio">No</label>
                                    </div>
                                </div>
                            </fieldset>
                            <div class="terms">
                                <div class="float-md-right">
                                    <span>I have read and agree to the <a href="#" class="agree"><b>Privacy Policy</b></a></span>
                                    <input type="checkbox" name="agree" value="1"> &nbsp;
                                    <input type="submit" value="Continue" class="return-customer-btn">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- Row End -->
            </div>
            <!-- Container End -->
        </div>
{% endblock %}

production_ecommerce/ecommerce/templates/ecommerce/food.html
{% extends "ecommerce/base/index-example.html" %}
{% block login %}
{% load static %}
{% load crispy_forms_tags %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link href="{% static 'css/profile.css'%}" rel="stylesheet" media="all">
<!------ Include the above in your HEAD tag ---------->

<!--
User Profile Sidebar by @keenthemes
A component of Metronic Theme - #1 Selling Bootstrap 3 Admin Theme in Themeforest: http://j.mp/metronictheme
Licensed under MIT
-->

<div class="container">
    <!-- Breadcrumb Start -->
    <div class="breadcrumb-area mt-30">
        <div class="container">
            <div class="breadcrumb">
                <ul class="d-flex align-items-center">
                    <li><a href="{% url 'ecommerce:home' %}">Home</a></li>
                    <li class="active"><a href="{% url 'ecommerce:food' %}">Order Food</a></li>
                </ul>
            </div>
        </div>
        <!-- Container End -->
    </div>
    <div class="row profile">
        <div class="col-md-9">
            <legend>Order Food</legend>
            <div class="profile-content">
                <div class="page-wrapper bg-gra-03 p-t-45 p-b-50">
                    <div class="card card-5">
                        <div class="card-body">
                            <form method="POST" action="{% url 'ecommerce:food' %}">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="form-group col-md-10 mb-0">
                                        {{ form.menu|as_crispy_field }}
                                    </div>
                                    <div class="form-group col-md-10 mb-0">
                                        {{ form.location|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="form-row">

                                    <div class="form-group col-md-10 mb-0">
                                        <label>*optional</label>
                                        {{ form.gps_address|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="form-row">

                                    <div class="form-group col-md-10 mb-0">
                                        {{ form.contact|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-6 mb-0">
                                        {{ formset.management_form }}
                                        {% for f in formset %}
                                        {{f.as_p}}
                                        {% endfor %}
                                    </div>

                                </div>
                                <div class="terms">
                                    <div class="float-md-right">
                                        <input type="submit" value="SUBMIT" class="return-customer-btn">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}